receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  jaeger:
    endpoint: "localhost:14250" # Jaeger endpoint for gRPC ingestion

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
